
class Config {

  /// Generated by Flangapp PRO {GENERATE_DATE}
  /// App UID: {APP_UID}
  /// Version: {VERSION}
  /// API server: {API_SERVER}

  /// *** Main settings *** ///
  static String apiUrl = "{API_SERVER}";
  static String appUid = "{APP_UID}";
  static String oneSignalPushId = "{ONESIGNAL_PUSH_ID}";

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "{SPLASH_BACKGROUND_COLOR}";
  // Text color (any HEX color)
  static String splashTextColor = "{SPLASH_TEXT_COLOR}";
  // Is image background
  static bool splashIsBackgroundImage = {SPLASH_IS_BACKGROUND_IMAGE};
  // Background image name
  static String splashBackgroundImage = "{SPLASH_BACKGROUND_IMAGE}";
  // Tagline
  static String splashTagline = "{SPLASH_TAGLINE}";
  // Delay display (seconds)
  static int splashDelay = {SPLASH_DELAY};
  // Logo image name
  static String splashLogoImage = "{SPLASH_LOGO_IMAGE}";
  // Display logo
  static bool splashIsDisplayLogo = {SPLASH_IS_DISPLAY_LOGO};

  /// *** Offline localization settings *** ///
  static String offlineErrorMessage = "{OFFLINE_ERROR_MESSAGE}";
  static String offlineImage = "{OFFLINE_IMAGE}";

  /// *** Subscribe need settings *** ///
  static String subscribeErrorTitle = "{SUBSCRIBE_ERROR_TITLE}";
  static String subscribeErrorMessage = "{SUBSCRIBE_ERROR_MESSAGE}";
}